name: Scrape latest chess data in JSON

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 13 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2

    - name: Fetch latest data in JSON format
      run: |-
        curl "https://lichess.org/api/games/user/TuttlePower?since=1525132800000&format=json" --output tuttlepower_games.json

    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
