name: Scrape latest chess data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 13 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
      
    - name: Get last game timestamp
      id: last_game_timestamp
      run: |
        # Extract the date of the last game from the .pgn file
        last_game_date=$(grep -oE "\[UTCDate \"[0-9]{4}\.[0-9]{2}\.[0-9]{2}\"\]" test_tuttlepower_games.pgn | tail -1 | grep -oE "[0-9]{4}\.[0-9]{2}\.[0-9]{2}")
        # Extract the time of the last game from the .pgn file
        last_game_time=$(grep -oE "\[UTCTime \"[0-9]{2}:[0-9]{2}:[0-9]{2}\"\]" test_tuttlepower_games.pgn | tail -1 | grep -oE "[0-9]{2}:[0-9]{2}:[0-9]{2}")
        # Convert the date and time to a Unix timestamp
        last_game_timestamp=$(date -u -d "${last_game_date} ${last_game_time}" +%s)
        echo "LAST_GAME_TIMESTAMP=$last_game_timestamp" >> $GITHUB_ENV

    - name: Fetch latest data
      run: |-
        curl https://lichess.org/games/export/TuttlePower?since=${{ env.LAST_GAME_TIMESTAMP }} --output new_games.pgn
        cat new_games.pgn >> test_tuttlepower_games.pgn

    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
